### ISSUE TITLE
Issue with genome index build

### ISSUE THREAD

**Issue by RajneeshSrivastava** [hellosunking/Msuite#2]
Hey team,

I am not sure, if the tool has been optimized for ensembl genome annotations. 

I did some formatting and prefixing with "**chr**" on individual chr<#>.fa.gz and the annotation.gtf.gz file.

```
#code
bash /N/project/Sen_Lab_Omics/RAJNEESH/Software/Msuite/build.index/build.index.sh -h
Usage: /N/project/Sen_Lab_Omics/RAJNEESH/Software/Msuite/build.index/build.index.sh <genome folder|fa> <refSeq.txt> <index.identifier> [thread=auto]

This is a utility program of Msuite, designed to build genome references.
Please refer to README file for more information.

#build index
bash /path/Msuite/build.index/build.index.sh /path/msuite_index/Genome_Dir/ /path/msuite_index/hg38_genes.txt.gz hg38
=> INFO: Threads used: 24
```
Except for thread information, I am getting no output. 

Any suggestion or pseudo code would be highly appreciated!

- Raj

**Comment by hellosunking** [comment]
Hi Raj,

The refSeq.txt is used to plot the DNA methylation signals around TSS (as a quick quality control),
therefore I do not recommand change it to ENSEMBLE. If you want to extract the DNA methylation
levels for each gene/promoters, you can use the utility programs in Msuite.

To build the index, the first parameter is the path of your genome sequences, either a folder that
contains all the fasta files for each chromosome (i.e., chr1.fa, chr2.fa ...), or one multi-fasta file that
contains all the chromsomes.  Msuite will automatically recognize the correct directory to store
the index files, then you can use this index via the 3rd parameter (index.identifier) in "-x" option.

Kun
