### ISSUE TITLE
CHH calling

### ISSUE THREAD

**Issue by AlsoATraveler** [hellosunking/Msuite#4]
Hello, can the software support CHH methylation calling ？

**Comment by hellosunking** [comment]
Yes, Msuite can do that. You can activate this function through the "--CpH" option.

However, Msuite is not maintained anymore. We recommend you change to its successor, Msuite2,
(https://github.com/hellosunking/Msuite2), which is much faster with more functionalities.

Kun

**Comment by AlsoATraveler** [comment]
Got it, thanks.
